name: calibre
version: '5.5.0'
summary: Calibre is a powerful and easy to use e-book manager.
description: |
  Calibre is a powerful and easy to use e-book manager.
  Users say it’s outstanding and a must-have. It’ll allow
  you to do nearly everything and it takes things a step
  beyond normal e-book software. It’s also completely
  free and open source and great for both casual users and
  computer experts.

base: core18
grade: devel
confinement: devmode
architectures:
  - build-on: amd64

apps:
  calibre:
    command: calibre
    command-chain:
      - bin/calibre-launch
    extensions:
      - kde-neon
    plugs:
      - browser-support
      - desktop
      - home
      - network
      - opengl
      - removable-media
      - x11

parts:
  calibre:
    plugin: dump
    source: https://github.com/kovidgoyal/calibre/releases/download/v5.5.0/calibre-5.5.0-x86_64.txz
    source-type: tar
    source-checksum: sha256/cc6514867350c50a996ac9cd093a63c40a62fff8086b6ec11e74028193e90991
    stage-packages:
      - libxi6
      - qt5-gtk-platformtheme

  launchers:
    after:
      - calibre
    plugin: dump
    source: snap/local/launchers/
    organize:
      '*': bin/
